### ISSUE TITLE
Remove references to stackoverflow-clone, and change styling.

### ISSUE THREAD

**Issue by Blakeinstein** [Upvision/community-front-end#1]
Most css needs to be changed.

Open for triage.

Please use #7 for tracking UI decisions and progress.

**Comment by shivamrajput177** [comment]
I want to contribute to this.

**Comment by Blakeinstein** [comment]
@shivamrajput177 Thanks for taking this up, remember to work on a separate branch from master.

Also I would suggest having one more person on this task.

**Comment by shivamrajput177** [comment]
Okay. I will try to find someone.

**Comment by Blakeinstein** [comment]
@shivamrajput177 The upvision logo exists in this repo, could you try to replace the logo and some minor css?

**Comment by shivamrajput177** [comment]
@Blakeinstein Okay

**Comment by Blakeinstein** [comment]
Follow #7 for those changes.

This has been resolved with #9 .
